import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { AgentActivity } from '../packages/react/src/AgentActivity.js';
import { ToolActivity } from '../packages/react/src/ToolActivity.js';
import { HumanOverride } from '../packages/react/src/HumanOverride.js';
import { RecoveryControl } from '../packages/react/src/RecoveryControl.js';
import { activity, recovery, stop, stopEvidence } from './supervision-fixtures.js';
import { controlRequest } from '../packages/react/src/supervision-contracts.js';

describe('activity presentation', () => {
  it('renders agent scope and partial effects', () => { render(<AgentActivity activity={activity} />); expect(screen.getByText(activity.effects)).toBeVisible(); });
  it('does not invent completion evidence', () => { render(<AgentActivity activity={{ ...activity, status: 'completed' }} />); expect(screen.getByRole('status')).toHaveTextContent('Outcome not verified'); });
  it('reports missing measurement rather than a percentage', () => { render(<AgentActivity activity={{ ...activity, progress: { completed: 6, total: 5, unit: 'steps' } }} />); expect(screen.getByText('Progress measurement unavailable.')).toBeVisible(); });
  it('renders tool category, target, authority and actor', () => { render(<ToolActivity activity={{ ...activity, tool: 'Fixture writer', category: 'writing', target: 'Local records', authority: 'Local only' }} />); expect(screen.getByText('Writing')).toBeVisible(); expect(screen.getByText('Local only')).toBeVisible(); });
  it('escapes supplied activity text', () => { const { container } = render(<AgentActivity activity={{ ...activity, task: '<script>alert(1)</script>' }} />); expect(container.querySelector('script')).toBeNull(); expect(screen.getByText('<script>alert(1)</script>')).toBeVisible(); });
});
describe('intervention and recovery requests', () => {
  it('never requests on mount', () => { const f = vi.fn(); render(<HumanOverride operation={stop} status="available" onRequest={f} />); expect(f).not.toHaveBeenCalled(); });
  it('emits a version-bound request without implying stoppage', async () => { const f = vi.fn(); render(<HumanOverride operation={stop} status="available" onRequest={f} />); fireEvent.click(screen.getByRole('button', { name: 'Request stop' })); await waitFor(() => expect(f).toHaveBeenCalledWith(controlRequest(stop))); expect(screen.queryByText('Stop confirmed')).toBeNull(); });
  it('blocks synchronous duplicate requests', async () => { const f = vi.fn(() => new Promise<void>(() => {})); render(<HumanOverride operation={stop} status="available" onRequest={f} />); const b = screen.getByRole('button', { name: 'Request stop' }); fireEvent.click(b); fireEvent.click(b); expect(f).toHaveBeenCalledTimes(1); expect(b).toBeDisabled(); });
  it('acknowledgement is not completion and remains latched', async () => { render(<HumanOverride operation={stop} status="available" onRequest={() => {}} />); fireEvent.click(screen.getByRole('button', { name: 'Request stop' })); await screen.findByText('Request acknowledged — result not confirmed'); expect(screen.getByRole('button', { name: 'Request stop' })).toBeDisabled(); });
  it('sanitizes rejected requests and blocks retry', async () => { render(<HumanOverride operation={stop} status="available" onRequest={() => Promise.reject(new Error('private-secret'))} />); fireEvent.click(screen.getByRole('button', { name: 'Request stop' })); await screen.findByText('Outcome unknown — do not repeat the request'); expect(screen.queryByText(/private-secret/)).toBeNull(); expect(screen.getByRole('button', { name: 'Request stop' })).toBeDisabled(); });
  it('does not accept completion without evidence', () => { render(<HumanOverride operation={stop} status="completed" onRequest={() => {}} />); expect(screen.getByRole('status')).toHaveTextContent('Outcome not verified'); });
  it('rejects evidence for another run', () => { render(<HumanOverride operation={stop} status="completed" evidence={{ ...stopEvidence, runVersion: '2' }} onRequest={() => {}} />); expect(screen.getByRole('status')).toHaveTextContent('Outcome not verified'); });
  it('shows confirmed stoppage only with bound evidence', () => { render(<HumanOverride operation={stop} status="completed" evidence={stopEvidence} onRequest={() => {}} />); expect(screen.getByRole('status')).toHaveTextContent('Stop confirmed'); });
  it('blocks same-version material changes', () => { const { rerender } = render(<HumanOverride operation={stop} status="available" onRequest={() => {}} />); rerender(<HumanOverride operation={{ ...stop, target: 'Different worker' }} status="available" onRequest={() => {}} />); expect(screen.getByRole('button', { name: 'Request stop' })).toBeDisabled(); expect(screen.getByRole('status')).toHaveTextContent('Review is stale'); });
  it('allows a reviewed new revision without inheriting confirmation', () => { const { rerender } = render(<HumanOverride operation={stop} status="completed" evidence={stopEvidence} onRequest={() => {}} />); rerender(<HumanOverride operation={{ ...stop, version: '2' }} status="available" onRequest={() => {}} />); expect(screen.getByRole('button', { name: 'Request stop' })).toBeEnabled(); expect(screen.queryByText('Stop confirmed')).toBeNull(); });
  it('blocks explicit host policy', () => { render(<HumanOverride operation={stop} status="available" blockedReason="Permission revoked" onRequest={() => {}} />); expect(screen.getByText('Permission revoked')).toBeVisible(); expect(screen.getByRole('button', { name: 'Request stop' })).toBeDisabled(); });
  it('expires without user activation', async () => { vi.useFakeTimers(); try { render(<HumanOverride operation={{ ...stop, expiresAt: new Date(Date.now() + 1000).toISOString() }} status="available" onRequest={() => {}} />); await act(async () => { vi.advanceTimersByTime(1002); }); expect(screen.getByRole('button', { name: 'Request stop' })).toBeDisabled(); } finally { vi.useRealTimers(); } });
  it('inspection cannot invoke the request callback', () => { const f = vi.fn(), inspect = vi.fn(); render(<HumanOverride operation={stop} status="unknown" onRequest={f} onInspect={inspect} />); fireEvent.click(screen.getByRole('button', { name: 'Inspect control status' })); expect(inspect).toHaveBeenCalledWith(controlRequest(stop)); expect(f).not.toHaveBeenCalled(); });
  it('inspection failure does not expose private exceptions', () => { render(<HumanOverride operation={stop} status="unknown" onRequest={() => {}} onInspect={() => { throw new Error('secret'); }} />); fireEvent.click(screen.getByRole('button', { name: 'Inspect control status' })); expect(screen.getByText(/Status inspection is unavailable/)).toBeVisible(); expect(screen.queryByText('secret')).toBeNull(); });
  it('unknown outcomes cannot be retried', () => { render(<RecoveryControl operation={{ ...recovery, kind: 'retry', originalOutcome: 'unknown' }} status="available" onRequest={() => {}} />); expect(screen.getByRole('button', { name: 'Request retry' })).toBeDisabled(); });
  it('permits a separate read-only reconciliation request', async () => { const f = vi.fn(); render(<RecoveryControl operation={{ ...recovery, kind: 'reconcile', originalOutcome: 'unknown' }} status="available" onRequest={f} />); fireEvent.click(screen.getByRole('button', { name: 'Check original action status' })); await waitFor(() => expect(f).toHaveBeenCalledTimes(1)); });
  it('calls compensation compensation, not undo', () => { render(<RecoveryControl operation={recovery} status="completed" evidence={{ ...stopEvidence, ...controlRequest(recovery) }} onRequest={() => {}} />); expect(screen.getByRole('status')).toHaveTextContent('Compensation confirmed — not undo'); });
  it('handles unmount during pending request', async () => { let resolve!: () => void; const f = vi.fn(() => new Promise<void>(r => { resolve = r; })); const { unmount } = render(<HumanOverride operation={stop} status="available" onRequest={f} />); fireEvent.click(screen.getByRole('button', { name: 'Request stop' })); unmount(); await act(async () => { resolve(); }); expect(f).toHaveBeenCalledTimes(1); });
});
