/** Compile-time parity: schema output must preserve every legacy serialized type. */
import type { z } from 'zod';
import type { WireSchemas } from './schemas.js';
type Mutable<T> = T extends object ? { -readonly [K in keyof T]: Mutable<T[K]> } : T;
type Equal<A, B> = (<T>() => T extends Mutable<A> ? 1 : 2) extends (<T>() => T extends Mutable<B> ? 1 : 2) ? true : false;
type Assert<T extends true> = T;
import type * as T0 from './contracts.js';
type CheckConsequence = Assert<Equal<T0.Consequence, z.output<typeof WireSchemas.Consequence>>>;
type CheckAutonomyLevel = Assert<Equal<T0.AutonomyLevel, z.output<typeof WireSchemas.AutonomyLevel>>>;
type CheckAgentState = Assert<Equal<T0.AgentState, z.output<typeof WireSchemas.AgentState>>>;
type CheckApprovalStatus = Assert<Equal<T0.ApprovalStatus, z.output<typeof WireSchemas.ApprovalStatus>>>;
type CheckReceiptStatus = Assert<Equal<T0.ReceiptStatus, z.output<typeof WireSchemas.ReceiptStatus>>>;
type CheckActor = Assert<Equal<T0.Actor, z.output<typeof WireSchemas.Actor>>>;
type CheckRecovery = Assert<Equal<T0.Recovery, z.output<typeof WireSchemas.Recovery>>>;
type CheckActionProposal = Assert<Equal<T0.ActionProposal, z.output<typeof WireSchemas.ActionProposal>>>;
type CheckDecisionRequest = Assert<Equal<T0.DecisionRequest, z.output<typeof WireSchemas.DecisionRequest>>>;
type CheckAgentProfile = Assert<Equal<T0.AgentProfile, z.output<typeof WireSchemas.AgentProfile>>>;
type CheckReceiptData = Assert<Equal<T0.ReceiptData, z.output<typeof WireSchemas.ReceiptData>>>;
import type * as T1 from './review-contracts.js';
type CheckRevisionRef = Assert<Equal<T1.RevisionRef, z.output<typeof WireSchemas.RevisionRef>>>;
type CheckReviewBasis = Assert<Equal<T1.ReviewBasis, z.output<typeof WireSchemas.ReviewBasis>>>;
type CheckContextAvailability = Assert<Equal<T1.ContextAvailability, z.output<typeof WireSchemas.ContextAvailability>>>;
type CheckContextUsage = Assert<Equal<T1.ContextUsage, z.output<typeof WireSchemas.ContextUsage>>>;
type CheckContextPersistence = Assert<Equal<T1.ContextPersistence, z.output<typeof WireSchemas.ContextPersistence>>>;
type CheckContextSource = Assert<Equal<T1.ContextSource, z.output<typeof WireSchemas.ContextSource>>>;
type CheckContextSnapshot = Assert<Equal<T1.ContextSnapshot, z.output<typeof WireSchemas.ContextSnapshot>>>;
type CheckPlanStatus = Assert<Equal<T1.PlanStatus, z.output<typeof WireSchemas.PlanStatus>>>;
type CheckPlanStepStatus = Assert<Equal<T1.PlanStepStatus, z.output<typeof WireSchemas.PlanStepStatus>>>;
type CheckPlanStep = Assert<Equal<T1.PlanStep, z.output<typeof WireSchemas.PlanStep>>>;
type CheckTaskPlan = Assert<Equal<T1.TaskPlan, z.output<typeof WireSchemas.TaskPlan>>>;
type CheckProposalStatus = Assert<Equal<T1.ProposalStatus, z.output<typeof WireSchemas.ProposalStatus>>>;
type CheckReviewRequest = Assert<Equal<T1.ReviewRequest, z.output<typeof WireSchemas.ReviewRequest>>>;
import type * as T2 from './evidence-contracts.js';
type CheckMemoryType = Assert<Equal<T2.MemoryType, z.output<typeof WireSchemas.MemoryType>>>;
type CheckMemoryState = Assert<Equal<T2.MemoryState, z.output<typeof WireSchemas.MemoryState>>>;
type CheckMemoryRecord = Assert<Equal<T2.MemoryRecord, z.output<typeof WireSchemas.MemoryRecord>>>;
type CheckMemoryInspectionRequest = Assert<Equal<T2.MemoryInspectionRequest, z.output<typeof WireSchemas.MemoryInspectionRequest>>>;
type CheckEvidenceAccess = Assert<Equal<T2.EvidenceAccess, z.output<typeof WireSchemas.EvidenceAccess>>>;
type CheckEvidenceRelationship = Assert<Equal<T2.EvidenceRelationship, z.output<typeof WireSchemas.EvidenceRelationship>>>;
type CheckEvidenceExcerpt = Assert<Equal<T2.EvidenceExcerpt, z.output<typeof WireSchemas.EvidenceExcerpt>>>;
type CheckEvidenceSource = Assert<Equal<T2.EvidenceSource, z.output<typeof WireSchemas.EvidenceSource>>>;
type CheckEvidenceCollection = Assert<Equal<T2.EvidenceCollection, z.output<typeof WireSchemas.EvidenceCollection>>>;
type CheckEvidenceState = Assert<Equal<T2.EvidenceState, z.output<typeof WireSchemas.EvidenceState>>>;
type CheckUncertaintyLevel = Assert<Equal<T2.UncertaintyLevel, z.output<typeof WireSchemas.UncertaintyLevel>>>;
type CheckUncertaintyAssessment = Assert<Equal<T2.UncertaintyAssessment, z.output<typeof WireSchemas.UncertaintyAssessment>>>;
import type * as T3 from './supervision-contracts.js';
type CheckActivityStatus = Assert<Equal<T3.ActivityStatus, z.output<typeof WireSchemas.ActivityStatus>>>;
type CheckActivityRecord = Assert<Equal<T3.ActivityRecord, z.output<typeof WireSchemas.ActivityRecord>>>;
type CheckToolCategory = Assert<Equal<T3.ToolCategory, z.output<typeof WireSchemas.ToolCategory>>>;
type CheckToolActivityRecord = Assert<Equal<T3.ToolActivityRecord, z.output<typeof WireSchemas.ToolActivityRecord>>>;
type CheckControlStatus = Assert<Equal<T3.ControlStatus, z.output<typeof WireSchemas.ControlStatus>>>;
type CheckControlRequest = Assert<Equal<T3.ControlRequest, z.output<typeof WireSchemas.ControlRequest>>>;
type CheckInterventionKind = Assert<Equal<T3.InterventionKind, z.output<typeof WireSchemas.InterventionKind>>>;
type CheckInterventionOperation = Assert<Equal<T3.InterventionOperation, z.output<typeof WireSchemas.InterventionOperation>>>;
type CheckRecoveryKind = Assert<Equal<T3.RecoveryKind, z.output<typeof WireSchemas.RecoveryKind>>>;
type CheckRecoveryOperation = Assert<Equal<T3.RecoveryOperation, z.output<typeof WireSchemas.RecoveryOperation>>>;
type CheckControlEvidence = Assert<Equal<T3.ControlEvidence, z.output<typeof WireSchemas.ControlEvidence>>>;
